version: '3.7'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  back:
    image: kurovale/kuro-paste
    environment:
      MONGODB_URL: mongodb://db/kuro-paste
      JWT_SECRET: veryVerySecret
    depends_on:
      - db
    ports:
      - "3000:3000"
  front:
    image: shiro-paste
    build: ./
    depends_on:
      - back
    ports:
      - "8080:8080"
